apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: docker-builder
spec:
  serviceAccountName: default
  containers:
    - name: jnlp
      image: jenkins/agent:latest-jdk11
    
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
  
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: workspace
      emptyDir: {}
