apiVersion: v1
kind: Pod
metadata:
  name: kaniko-jenkins-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args:
        - ${computer.jnlpmac}
        - ${computer.name}
      env:
        - name: JENKINS_URL
          value: "http://jenkins.ci-cd.svc.cluster.local:8080/"
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command: ["sh", "-c"]
      args: ["while true; do sleep 300; done;"]
      workingDir: /home/jenkins/agent
      volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1536Mi"
  volumes:
    - name: workspace-volume
      emptyDir: {}
